services:
  playerinstancer:
    build:
      context: .
      dockerfile: playerinstancer/Dockerfile
    volumes:
      # Allow managing docker from inside container. 
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "1000:22"
  icebreaker:
    build:
      context: .
      dockerfile: icebreaker/Dockerfile
    ports:
      - "802${INSTANCE_NUM:-2}:8080"
    networks:
      iso:
        ipv4_address: 10.2.0.${INSTANCE_NUM:-2}
  telephone:
    build:
      context: .
      dockerfile: telephone/Dockerfile
    ports:
      - "803${INSTANCE_NUM:-2}:8080"
    networks:
      iso:
        ipv4_address: 10.3.0.${INSTANCE_NUM:-2}
networks:
  iso:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/8
          ip_range: 10.100.0.0/16
          gateway: 10.0.0.1
    attachable: true
    name: iso