services:
  playerinstancer:
    build:
      context: .
      dockerfile: playerinstancer/Dockerfile
    volumes:
      # Allow managing docker from inside container. 
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "1111:22"